### ISSUE TITLE
sshsession how to restore

### ISSUE THREAD

**Issue by simonfangyingzhang** [darkoperator/Posh-SSH#157]
Hi Guru,

new-sshsession to create 1 ssh session, sometimes it may be disconnected due to intermittent networking failure, is there any way to restore this session? many thanks

**Comment by darkoperator** [comment]
If a key was not used the credentials are included in the session object as well as the host info, you just use that same information to connect back and replace the broken the session in the global variable that keeps track of the sessions. 

From: simonfangyingzhang
Sent: Tuesday, July 11, 2017 5:53 AM
To: darkoperator/Posh-SSH
Cc: Subscribed
Subject: [darkoperator/Posh-SSH] sshsession how to restore (#157)

Hi Guru,
new-sshsession to create 1 ssh session, sometimes it may be disconnected due to intermittent networking failure, is there any way to restore this session? many thanks

**Comment by simonfangyingzhang** [comment]
thank you sir, looks like I still can issue linux commands even sshsession.connected false, no problem now, thanks
