### ISSUE TITLE
Invoke-SSHExpectSecureAction - SecureAction Parameter Disposes of SecureString

### ISSUE THREAD

**Issue by bwright86** [darkoperator/Posh-SSH#160]
I noticed that the `Invoke-SSHExpectSecureAction` function calls the `dispose() `method of the `[SecureString]` object that is passed for the `-SecureAction`.

This could be an issue if the password property of a `[PSCredential]` object is passed as the `-SecureAction`. The `[PSCredential]` is managed outside of this function, but the function is disposing of the object.

Looking at documentation for `[SecureString]` objects, it appears these objects are mutable and encrypted in memory. They can be decrypted for use. It seems these objects are implicitly passed by reference, so it is not a copy of the object that is being disposed of by the function.

I would like to suggest removing this line from the `Invoke-SSHExpectSecureAction` function:
[Posh-SSH.psm1:838](https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH.psm1#L838)             `$SecureAction.Dispose() `

Or at least handle it differently for these two scenarios:
**Scenario 1:** 
`Invoke-SSHExpectSecureAction -SecureAction $(get-credential | select -expand Password)`
(It could make sense for the function to dispose of this object for the user.)

**Scenario 2:** 
`$cred = get-credential`
`Invoke-SSHExpectSecureAction -SecureAction $($cred.Password)`
(It does not make sense to dispose of the object in this case, user should dispose when done with credential.)

**Comment by thecliguy** [comment]
I'm also facing a problem due to the presence of `Dispose`.

I believe that @bwright86 is refering to `Invoke-SSHStreamExpectSecureAction`, not `Invoke-SSHExpectSecureAction`.

As bwright86 has explained, when calling `Invoke-SSHStreamExpectSecureAction` the object supplied to the `-SecureAction` parameter, PowerShell implicitly passes by reference. Consequently when `Dispose` is called the object is destroyed outside the scope of the function.

Also - because the dispose is within the process block, pipeline input ByPropertyName would fail after the first iteration if the `SecureAction` property of each object were to reference the same object, EG:

```
$Server = "example"
$SSHCredential = Get-Credential

Import-Module Posh-SSH

$Session = (New-SSHSession -ComputerName $Server -Port 22 -Credential $SSHCredential -ConnectionTimeout 60)

$Stream = New-SSHShellStream -SSHSession $Session

$secstr = ConvertTo-SecureString 'echo hello' -asplaintext -force

@(
    [PSCustomObject] @{ SecureAction = $secstr }
    [PSCustomObject] @{ SecureAction = $secstr }
    [PSCustomObject] @{ SecureAction = $secstr }
) | Invoke-SSHStreamExpectSecureAction `
	-ShellStream $Stream `
	-Command "uname" `
	-ExpectString "Linux" `
	-Timeout 20 `
	-Verbose;

$Stream.Dispose()

Remove-SSHSession -SessionID $Session.SessionID
```

Unless there is a justification for the presence of `Dispose`, can you consider removing it?

**Comment by darkoperator** [comment]
Will do in the next version

**Comment by bwright86** [comment]
Thanks for the quick response. For now I have removed this line in the module I use locally.

@thecliguy is correct it is the `Invoke-SSHStreamExpectSecureAction` function. It is just a lot of nouns to remember :-) but seems necessary to get the point across of what it does.

I have enjoyed this module ever since my company started using Linux/Unix more, it seems to work well with it.

**Comment by bwright86** [comment]
Hey @darkoperator,

Looks like you updated your module, and corrected this issue. I need to download it and try out the updates, but this issue can be closed.

Thanks!
