### ISSUE TITLE
Exception calling "EndExecute" with "1" argument(s): has timed out

### ISSUE THREAD

**Issue by thefossgeek** [darkoperator/Posh-SSH#163]
Hi All, I am using the below code to SSH to Linux server and run a bash script which may take to complete 5 mins to 45 mins based on argument to script.  It seems Invoke-SSHCommand runs the  command and exit immediately with the following error:

Exception calling "EndExecute" with "1" argument(s): "Command '/opt/install.sh  <list of option and arguments>' has timed out."

I am not able to find what exactly I am doing wrong. Any help will be really appreciated.

Is there any way to force Invoke-SSHCommand to wait till it will complete script execution? How to achieve to wait untill the remote script completes execution?
 
`Function Invoke-RemoteServer {

Param (
    [Parameter(Mandatory=$true,Position=0)][string]$HostName,
    [Parameter(Mandatory=$true,Position=1)][int]$Port,
    [Parameter(Mandatory=$true,Position=2)][string]$UserName,
    [Parameter(Mandatory=$true,Position=3)][string]$Password,
    [Parameter(Mandatory=$true,Position=4)][string]$Command
  )
 
Process {

\# Generate credentials object for authentication
$SecPasswd   = ConvertTo-SecureString $Password -AsPlainText -Force

$Credentials = New-Object System.Management.Automation.PSCredential ($UserName, $secpasswd) 
   
Try {

$Session = New-SSHSession -Computername $HostName -Credential $Credentials -Port $Port -Force

}
Catch {

 $LogMsg = "New-SSHSession failed Msg: $($_.Exception.Message)"

 Write-Host $LogMsg 
 
 Exit

  }

Try {

 Store the output of the command 
$Output = (Invoke-SSHCommand -SSHSession $Session -Command $Command).Output

 }
Catch {

$LogMsg = "Invoke-SSHCommand failed Msg: $($_.Exception.Message)"
    
Write-Host $LogMsg

Exit 

 }
	
  \# Remove the session after we're done
  Remove-SSHSession -Name $Session | Out-Null 

  \# return the actual output
  \#Write-Host $Output.Trim()

  $sshOutput = $Output.Trim()

  return $sshOutput

  }

}

\# Script to run on target server
\# 
$ssh_cmd = "/opt/install.sh  <list of option and arguments>"

Try {

$sshOutput = Invoke-RemoteServer -HostName $host_name -Port $ssh_port -UserName $user_name -Password $user_password -Command "$ssh_cmd"

Write-Host "Successfull......"

}
Catch {

Write-Host "Invoke-RemoteServer failed"

}`

**Comment by darkoperator** [comment]
For this case a shell stream would be better, since the stream is a full TTY terminal you can write and read from with no timeout. You would just need to monitor the stream until you get the prompt indicating that it finished. 

From: Mohan L
Sent: Thursday, August 3, 2017 9:43 AM
To: darkoperator/Posh-SSH
Cc: Subscribed
Subject: [darkoperator/Posh-SSH] Exception calling "EndExecute" with "1"argument(s): has timed out (#163)

Hi All, I am using the below code to SSH to Linux server and run a bash script which may take to complete 5 mins to 45 mins based on argument to script. It seems Invoke-SSHCommand runs the command and exit immediately with the following error:
Exception calling "EndExecute" with "1" argument(s): "Command '/opt/install.sh ' has timed out."
I am not able to find what exactly I am doing wrong. Any help will be really appreciated.
Is there any way to force Invoke-SSHCommand to wait till it will complete script execution? How to achieve to wait untill the remote script completes execution?
Function Invoke-RemoteServer {
Param (
[Parameter(Mandatory=$true,Position=0)][string]$HostName,
[Parameter(Mandatory=$true,Position=1)][int]$Port,
[Parameter(Mandatory=$true,Position=2)][string]$UserName,
[Parameter(Mandatory=$true,Position=3)][string]$Password,
[Parameter(Mandatory=$true,Position=4)][string]$Command
)
Process {
Generate credentials object for authentication
$SecPasswd = ConvertTo-SecureString $Password -AsPlainText -Force
$Credentials = New-Object System.Management.Automation.PSCredential ($UserName, $secpasswd)
Try {
$Session = New-SSHSession -Computername $HostName -Credential $Credentials -Port $Port -Force
}
Catch {
$LogMsg = "New-SSHSession failed Msg: $($_.Exception.Message)"

Write-Host $LogMsg 

Exit
}
Try {
# Store the output of the command 
$Output = (Invoke-SSHCommand -SSHSession $Session -Command $Command).Output
}
Catch {
$LogMsg = "Invoke-SSHCommand failed Msg: $($_.Exception.Message)"

Write-Host $LogMsg

Exit 
}
Remove the session after we're done
Remove-SSHSession -Name $Session | Out-Null
return the actual output
#Write-Host $Output.Trim()
$sshOutput = $Output.Trim()
return $sshOutput
}
}
Script to run on target server
$ssh_cmd = "/opt/install.sh "
Try {
$sshOutput = Invoke-RemoteServer -HostName $host_name -Port $ssh_port -UserName $user_name -Password $user_password -Command "$ssh_cmd"

Write-Host "Successfull......"
}
Catch {
Write-Host "Invoke-RemoteServer failed"
}

**Comment by thefossgeek** [comment]
Thanks for your time. are you referring to use New-SSHShellStream? Is there any example about how to use New-SSHShellStream?

**Comment by darkoperator** [comment]
In the README File for the project there is 

Here is an example on how I use it for running commands on VyOS
https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb
