### ISSUE TITLE
New Posh-SSH release to support new key exchange algorithms from upstream lib SSH.NET

### ISSUE THREAD

**Issue by dbrennand** [darkoperator/Posh-SSH#338]
This issue relates to #314 

Has a new version of SSH.NET been released so additional key exchange algorithms are supported?

**Comment by darkoperator** [comment]
Check the beta 1 release in gallery and here in github :)

**Comment by dbrennand** [comment]
Cool, I will test on Monday 😉

**Comment by dbrennand** [comment]
Did some testing. Seems alright apart from one issue. I commented here: https://github.com/darkoperator/Posh-SSH/issues/329#issuecomment-651093666

**Comment by darkoperator** [comment]
-Force will simply not check if the key is valid and will not even save it if -AcceptKey is specified so my guess it is in the key format but if it works at the end that is the part that is confusing. Will try to generate a RSA key in the old OpenSSH format since the new one is only supported for Curve keys and try to authenticate with that, sadly SSH.Net <http://ssh.net/> sis not add support for the new format for DSA and RSA kets. There is no deep SSH inspection like a Fortinet device in front of the server? Seen that break

**Comment by dbrennand** [comment]
No nothing like that in front of the server.

**Comment by dbrennand** [comment]
This issue is resolved.
The `-Force` parameter is a good workaround. I believe the issue resolved when I re-deployed the piece of infrastructure.
