### ISSUE TITLE
Port forwarding commands are not exported

### ISSUE THREAD

**Issue by eosfor** [darkoperator/Posh-SSH#35]
is it correct, is it supposed to work like this?

**Comment by darkoperator** [comment]
yes this is to be expected, if you look in the code and the changeling of previous version I note that the library I use is broken on that side and I'm waiting for them to fix it for .Net 3.5. Supporting PowerShell 2.0 for all the people that mentioned that they can not upgrade has limited this functionality since it is fixed for .Net 4.0 but not 3.5. No ETA on when.

**Comment by eosfor** [comment]
Sorry, just realized, do you mean it works for PS 3 and above

**Comment by eosfor** [comment]
May I ask you to give me an example of the mentioned behavior. Steps to reproduce so to speak.

**Comment by darkoperator** [comment]
Just create a dynamic port forward, set your browser to use the port forward as a SOCKS Proxy and browse a bit. You will see as connections are left open in wait state using netstat to monitor
