### ISSUE TITLE
Key exchange negotiation failed

### ISSUE THREAD

**Issue by benchisler** [darkoperator/Posh-SSH#353]
When running this script in interactive mode in PowerShell ide it connects and transfers files.  When using the same user as a scheduled task I get the  "Key exchange negotiation failed"

# Define Serve Name
$ComputerName = "where.my.server.is"

# Define UserName
$UserName = "user.name"

#Define the Private Key file path
$KeyFile = "C;\helpdesk.txt"
$nopasswd = new-object System.Security.SecureString

#Set Credetials to connect to server
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $nopasswd)

# Set local file path, SFTP path, and the backup location path which I assume is an SMB path
$FilePath = "$SharePath"
$SftpPath = '.'

# Establish the SFTP session
$SFTPSession = New-SFTPSession -ComputerName $ComputerName -Credential $Credential -KeyFile $KeyFile -Port 22 -AcceptKey

# Upload the file to the SFTP path
Set-SFTPFile -SessionId $SFTPSession.SessionID -LocalFile $FilePath -RemotePath $SftpPath -Overwrite

# Disconnect SFTP session
$SFTPSession.Disconnect()

any suggestions?

**Comment by darkoperator** [comment]
What encryption and version is the key? Also a key with no passphrase o_O is that correct?

**Comment by benchisler** [comment]
No passphrase, how to i check the encryption?

**Comment by darkoperator** [comment]
I don’t think the library supports no passphrase keys. Never done that, even in lab environments 

ssh-keygen -l -f ~/.ssh/id_rsa.pub

**Comment by benchisler** [comment]
So I believe that it is RSA 2048

**Comment by darkoperator** [comment]
The library does not support the new format RSA, it does the old one and the new elliptical keys. Wonder if it could be that.  They have an issue open for it 

https://github.com/sshnet/SSH.NET/pull/614#pullrequestreview-413793384 <https://github.com/sshnet/SSH.NET/pull/614#pullrequestreview-413793384>

**Comment by benchisler** [comment]
Carlos,

Thanks for looking into this I will redo the key and see if that fixes the
problem. One question is why would the encryption only be an issue when
running as a scheduled task but not when running interactively through
PowerShell ise?

**Comment by MikeMM70** [comment]
Are you running the scheduled task as the same user you are running the ISE
under? If not, do they have different keys?

Michael M. Minor

**Comment by darkoperator** [comment]
As someone who’s day job is writing offensive tooling some of the capabilities of our implants are to enumerate schedules tasks, if we see that we will go after that key and use it for lateral movement. A way to protect it is to store the key protected with a password, then the credential file is protected with a certificate stored in the system certificate store and the taks ran as system, that way is an attacker gets in he would need to provilege escalate to system which is a lot more consuming and then get to the certificate store and pull out the cert to decrypt the credential file which is various levels more complex and would affect greatly an attacker tempo. I would avoid DPAPI since there is a ton of tools to abuse it and that is what exporting a pscredential object uses.

**Comment by benchisler** [comment]
I want to thank you for your help.  I have been able to resolve this
temporarily with the -force switch.  So I think the issue may be host
key validation.  Where does Posh-ssh look to validate keys so I can add the
fingerprint.? We appear to be running version 1.0.  Would thins be fixed by
moving to 2.1 and  using the  New-SSHTrustedHost.md
<https://github.com/darkoperator/Posh-SSH/blob/master/docs/New-SSHTrustedHost.md>.
Again, thank you for all of your help

**Comment by darkoperator** [comment]
Yes there are functions to list, remove and add fingerprints
