### ISSUE TITLE
Running the command in vCenter

### ISSUE THREAD

**Issue by Morrison2010** [darkoperator/Posh-SSH#361]
Hello, 
Good Morning. I am new to Posh-SSH
/usr/lib/vmware-vmafd/bin/vecs-cli entry list --store MACHINE_SSL_CERT --text | less
I want to run the above command in my vCenter via this Posh-SSH.
Can someone please help me how to run this (Again I have 0 exp in posh-ssh). So appreciate if you can tell me how to:
1. Connect the vCenter using root account
2. Run the command
3. Disconnect the session

**Comment by darkoperator** [comment]
The less command would not work, posh-ssh does not support paging, it is for running a command and getting the output as an object. 

https://www.youtube.com/watch?v=aZT5L_0aepE <https://www.youtube.com/watch?v=aZT5L_0aepE>

Even do the article is an old one it still follows the commands that one would use. Installation is via the install-module cmdlet
https://www.powershellmagazine.com/2014/07/03/posh-ssh-open-source-ssh-powershell-module/ <https://www.powershellmagazine.com/2014/07/03/posh-ssh-open-source-ssh-powershell-module/>

**Comment by Morrison2010** [comment]
Thank you for the reply Carloz,
I am not sure what does that mean : "does not support paging". The command which I have pasted is for getting the vCenter Machine SSL cert expiry date. if we connect the vCenter via SSH and run the above command then we would get the expiry date. 
So are you saying we cannot run the above command for vCenter Appliance ?

**Comment by darkoperator** [comment]
The less command is used to page the output one screen at a time and you use the keyboard to move back and forth, so no piping to less

**Comment by Morrison2010** [comment]
Hello Carloz,
Good Morning! 
If that is the case can I run the command without '| less':
**/usr/lib/vmware-vmafd/bin/vecs-cli entry list --store MACHINE_SSL_CERT --text**

If so, can you please let me know how can I run the command?

**Comment by darkoperator** [comment]
I gave you the info on the links in one of the replies :)

**Comment by Morrison2010** [comment]
Hello Carloz,
I am getting this. Any help ?
![image](https://user-images.githubusercontent.com/76489204/103226383-fc301c00-48f9-11eb-81cb-e84ac9e43108.png)

**Comment by darkoperator** [comment]
No clue that error is the host it self returning it not posh-ssh. Have you tried a shell stream? In case it depends on a propper shell and not elf binary execution

**Comment by Morrison2010** [comment]
I can run the command from SSH (Putty session). But not from the powershell (Posh-SSH)

**Comment by darkoperator** [comment]
Then more than likely it requires a shell, putty is a full terminal shell, Invoke-sshcommand is more like plink where it simply executes the binary given with parameters and there is no state. You will have to create a session then a shell stream from the session and treat it like a stream 

https://github.com/darkoperator/Posh-SSH/blob/master/docs/New-SSHShellStream.md <https://github.com/darkoperator/Posh-SSH/blob/master/docs/New-SSHShellStream.md>

https://github.com/darkoperator/Posh-SSH/blob/master/docs/Invoke-SSHStreamShellCommand.md <https://github.com/darkoperator/Posh-SSH/blob/master/docs/Invoke-SSHStreamShellCommand.md> no need to specify a promp pattern here since it is linux, so the default should work

**Comment by darkoperator** [comment]
reopen if still needed
