### ISSUE TITLE
Key Fingerprint handling 3.0

### ISSUE THREAD

**Issue by darkoperator** [darkoperator/Posh-SSH#362]
Thanks to a code contribution for 3.0 thinking of using the IStore Method from the Pull Request I merged in to a branch. So far planning:

- Memory IStore so one can be created a multiple host and fingerprints can be set and used. 
- JSON IStore same concept as memory but it will load and save keys from a JSON file. 
- Use the $Home/.possh/hosts.json file as the default place for fingerprint storage since $HOME exists in Linux, MacOS, Windows and PowerShell Azure Cloud Shell.
- Fingerprint management cmdlets will work with  $Home/.possh/hosts.json

This next major version will only be for the latest version of PowerShell, Windows PowerShell will be dropped.

**Comment by MVKozlov** [comment]
may be **.ssh/known_hosts** in Open-SSH format will be better default ?

**Comment by darkoperator** [comment]
To much pain, have you read the standard for it? :P i hardly have time to maintain the module so ai am going with MVP (minimum viable product)

**Comment by MVKozlov** [comment]
I don't see much of a problem in the implementation, but hashed hostnames violate the ISTore interface's GetKeys() method
(If we do not want to support @cert-authority). It should be changed to GetKey(hostname) or something similar.
If this interface can be changed I even try to implement it... when I have a time :)

**Comment by darkoperator** [comment]
In terms of value is there one? SSH.Net <http://ssh.net/> does not support cert validate with a Cert Authority, in fact it does not even support all the key formats and ciphers that OpenSSH does. They are 2 different projects with different goals. SSH.Net <http://ssh.net/> only allows me to compare a fingerprint using an event outside of that is does not provide any further validation. It does not even let me control de hash and encryption and even less it  does not support key generation.

**Comment by MVKozlov** [comment]
A predefined set of host keys that are already set manually are good for automation. And Openssh supports wildcards.

I quickly looked through the sources and realized that maintaining `SetKey()` can be painful, So I take back my words of a good default. This can be done since the public key is also passed in the `.Data` field, but not worth the effort.

It seems the fingerprint is always computed as **md5** [here] (https://github.com/sshnet/SSH.NET/blob/d62594c03f502338d069b5462525744acb075c07/src/Renci.SshNet/Common/HostKeyEventArgs.cs#L59)

So I can try to make the read-only `OpenSSHKeystore` if you let me change the `IStore` interface to `string GetKey(hostname)` instead of `IDictionary GetKeys()`. In any case, returning a mutable collection via an interface is not very good.

**Comment by darkoperator** [comment]
I would say go for it :) thanks for looking in to it and offering to help.

**Comment by MVKozlov** [comment]
Now I know what you meant when you said, "It doesn't even allow me to control the hash and encryption." :)

[There is it](https://github.com/sshnet/SSH.NET/blob/d62594c03f502338d069b5462525744acb075c07/src/Renci.SshNet/ServiceFactory.cs#L103)

The library actually selects the first host key it finds. And it does not match the OpenSSH default (_ssh-ed25519_ vs _ecdsa-sha2-nistp256_)

So only the **known_hosts** created with `ssh-keyscan` would be suitable for use, but not already existing on most live hosts.

btw, it almost done, I wait for @soynerdito finished his work on interface.
I think `.GetKeys()` should be completely removed.

And may be move fingerprint validation inside *Storages ? something like `ValidateKey(hostname, fingerprint)` which return `Accepted/Denied/Unknown` states.

**Comment by MVKozlov** [comment]
@darkoperator please view my latest PR # 369
I've implemented pretty much everything we've discussed here.

Some thoughts on:
- Additional assemblies do not seem to be loaded from the Assembly / folder. For my tests, I put them next to PoshSSH.dll
- I don't like the names of the `New-SSHxxxStore` cmdlets, because apart from memory they are not quite "New"
- Particularly disliked by my `New-SSHOpenSSHStore`. Too much SSH for me :)
- I think that all of this should be renamed to `Verb-SSHxxxKeyStore` to more accurately reflect their purpose and to do the same with the `-Store` parameter
- I don't know which verb to use. maybe `Get-`
- `New-SSHTrustedHost` and `Remove-SSHTrustedHost` can easily be implemented with an additional interface method, `RemoveKey`. But `Get-SSHTrustedHost` can not. Or will have to return GetAllKeys method. But not for OpenSSH

**Comment by darkoperator** [comment]
Compiled the PR and got this error

```
1>------ Build started: Project: PoshSSH.Core, Configuration: Debug Any CPU ------
1>PoshSSH.Core -> C:\Users\Carlos Perez\Documents\GitHub\Posh-SSH\Source\PoshSSH\PoshSSH.Core\bin\Debug\netstandard2.0\PoshSSH.dll
2>------ Build started: Project: PoshSSH, Configuration: Debug Any CPU ------
2>C:\Users\Carlos Perez\Documents\GitHub\Posh-SSH\Source\PoshSSH\PoshSSH\Stores\RegistryStore.cs(7,34,7,47): error CS0535: 'RegistryStore' does not implement interface member 'IStore.SetKey(string, string, string)'
2>C:\Users\Carlos Perez\Documents\GitHub\Posh-SSH\Source\PoshSSH\PoshSSH\Stores\RegistryStore.cs(7,34,7,47): error CS0738: 'RegistryStore' does not implement interface member 'IStore.GetKey(string)'. 'RegistryStore.GetKey(string)' cannot implement 'IStore.GetKey(string)' because it does not have the matching return type of 'Tuple<string, string>'.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

- **New** means that new object is created. in this case a new one is created from a file. 
- I know, having been burned before by cmdlet name conflicts I think we can keep all the SSHs
- I like the rename idea I think I will make the changes

If we go by the verb definitions from MS, I think New fits it because if it does not exist it will be created. 
```
Verb        AliasPrefix Group          Description
----        ----------- -----          -----------
New         n           Common         Creates a resource
Get         g           Common         Specifies an action that retrieves a resource
```

I do want to get rid of the registry store completely so the error may be none important. 

yep, still need to give a way to manage the existing keys in a store.

**Comment by darkoperator** [comment]
Should I do the extra changes or are you interested in making those?

**Comment by darkoperator** [comment]
now that I think of Verb-SSHxxxKeyStore I think key may not be the right word, since it is not keys but fingerprints what we keep. instead of KeyStore, maybe KnownHost

**Comment by darkoperator** [comment]
making the changes of removing the registry store and changing the command names from Store to KnownHost will be commiting often the changes

**Comment by MVKozlov** [comment]
I make separated `PoshSSH_std.sln` for netstandard.20 library only
and because Registry Store is deprecated (because it cannot be used on Linux/Core)
I wrote `Release\Get-SSHRegistryKeyStore.ps1` which replace this class

**Comment by MVKozlov** [comment]
I think `Verb-SSHxxxKhownHost` or `Verb-SSHxxxKhownHostStorage` will be good naming
But the second option is too long for my taste

for now, OpenSSH and Registry functions are read-only, so I believe it should be Get
and Memory can be New- because it cannot be saved.

For Json, both words don't quite match the behavior;
on the one hand - it can create a file if it does not exists (new)
on the other hand, if the file already exists, it will be read (get)

so, as you like, but I like `Get` more.

**Comment by soynerdito** [comment]
I believe we might be able to use preprocessor directives so certain codes can be filtered depending on either target platform or framework used. Then build something like "legacy".
However since it sounds Registry should be deprecated, if needed we can provide a way for the users to migrate their store. I am assuming it can be handled.

**Comment by MVKozlov** [comment]
and for key management.
If we need `Get-SSHTrustedHost -Store xxx` there is need for GetHostnames in interface. But OpenSSH often have cryptic hostnames inside. This may lead to additional support questions.

**Comment by MVKozlov** [comment]
@soynerdito, because there is a plans for dropping legacy and leave the only netstandatd2.0 platform then old project can be fully dropped at any time.
I couldn't take on such a responsibility  :)
And, as I already said, for the upgrade, I wrote the appropriate cmdlets

**Comment by darkoperator** [comment]
ok after mulling it over yes Get makes sense for those. Made some minor changes. Next steps before a beta release in the galley next week is:

- Make the objects returned by the knownhost to have proper properties so it is not Item1 Item2.
- Add getall method to memory json and openssh
- Add remove method to json and openssh
- Update the cmdlets for removing and adding known hosts.

I think with those changes I can push a beta. Then work in addressing other issues. @MVKozlov can you add the first 3 to the code since you have been refactoring that code? I can update the functions once that is done and prep a Beta release for the gallery.

**Comment by MVKozlov** [comment]
@darkoperator, yes I can. may be tomorrow.
Move from Item1, Item2 require change `Tuple<string, string>` to `struct`

**Comment by soynerdito** [comment]
If you want to try, you may still use named Tupples, just a few refactor.
On yout IStore may use
(string HostKeyName, string Fingerprint ) GetKey(string Host);

And just remove the word Tupple<string,string> by using just parentesis()

For example
insted of:
private ConcurrentDictionary<string, Tuple<string, string>> hostKeys;
private ConcurrentDictionary<string, (string hostKeyName, string fingerprint)> hostKeys;

and
 var hostData = new Tuple<string, string>(keyName, tmpFingerprint);
to:
var hostData = (keyName, tmpFingerprint);

Just saying, still may use a more formal like a class or struct.
