### ISSUE TITLE
New-SSHSession - Connection attempt failed because the connect party did not respond properly....

### ISSUE THREAD

**Issue by LuisAmaroUC** [darkoperator/Posh-SSH#410]
I'm running the following command in a runbook within an azure automation account.

New-SSHSession -ComputerName "xxxxx" -Credential xxx -Port 22 -AcceptKey:$true -ConnectionTimeout 100 -Force -KeepAliveInterval 100 -OperationTimeout 100

And i´m getting the following error:

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because the host has failed to respond.

Do you have any idea of what's happening?

**Comment by darkoperator** [comment]
Anything on the target box logs? Sent from Mail for Windows 10 From: LuisAmaroUCSent: Wednesday, July 28, 2021 10:15 AMTo: darkoperator/Posh-SSHCc: SubscribedSubject: [darkoperator/Posh-SSH] New-SSHSession - Connection attempt failed because the connect party did not respond properly... (#410) I'm running the following command in a runbook within an azure automation account.New-SSHSession -ComputerName "xxxxx" -Credential xxx -Port 22 -AcceptKey:$true -ConnectionTimeout 100 -Force -KeepAliveInterval 100 -OperationTimeout 100And i´m getting the following error:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because the host has failed to respond.Do you have any idea of what's happening?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LuisAmaroUC** [comment]
It appears that there no issues on the VM, since I can connect to it using Putty. I´m trying to connect to a Linux VM, and I already tried different version of Posh-ssh (2.3.0 , 3.0.0-beta1, 3.0.0-beta2 ).

**Comment by darkoperator** [comment]
But on the linux host anything on the logs? What version of linux, what version of openssh on it, what are the algorithms of the host key … etc need info to be able to reproduce it
