### ISSUE TITLE
Invoke-SSHStreamExpectSecureAction: problem with Renci.SshNet.ShellStream

### ISSUE THREAD

**Issue by Boppel** [darkoperator/Posh-SSH#423]
I have a very weird issue with Posh-SSH 3.0.0 on _one_ of my machines.
Running
`Invoke-SSHStreamExpectSecureAction -ShellStream $stream -Command "sudo su -" -ExpectString "[sudo] Password" -SecureAction $wayne`

on my local machine: perfect.
on a windows vm: nope:
`Invoke-SSHStreamExpectSecureAction : Cannot process argument transformation on parameter 'ShellStream'. Cannot convert the "Renci.SshNet.ShellStream" value of type 
"Renci.SshNet.ShellStream" to type "Renci.SshNet.ShellStream".`

snippet is working fine on different windows vm, uninstalled & re-installed posh-ssh module, restarted machine, no success so far.

this must be something _very_ trivial, but I'm really stuck here :/

**Comment by MVKozlov** [comment]
seems this is PSv5.1 and somewhere (may be in IL cache) you have another copy of `Renci.SshNet.dll`

**Comment by darkoperator** [comment]
What version of Windows is the VM? Sent from Mail for Windows From: Felix BeifußSent: Monday, September 20, 2021 10:40 AMTo: darkoperator/Posh-SSHCc: SubscribedSubject: [darkoperator/Posh-SSH] Invoke-SSHStreamExpectSecureAction: problem with Renci.SshNet.ShellStream (#423) I have a very weird issue with Posh-SSH 3.0.0 on one of my machines.RunningInvoke-SSHStreamExpectSecureAction -ShellStream $stream -Command "sudo su -" -ExpectString "[sudo] Password" -SecureAction $wayneon my local machine: perfect.on a windows vm: nope:Invoke-SSHStreamExpectSecureAction : Cannot process argument transformation on parameter 'ShellStream'. Cannot convert the "Renci.SshNet.ShellStream" value of type "Renci.SshNet.ShellStream" to type "Renci.SshNet.ShellStream".snippet is working fine on different windows vm, uninstalled & re-installed posh-ssh module, restarted machine, no success so far.this must be something very trivial, but I'm really stuck here :/—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Boppel** [comment]
Hi,

sorry for those missing information in my first post.

**affected vm**
- os: windows server 2019 (1809)
- powershell ver: 5.1.17763.2090

Could it be that **Renci.SshNet.dll** (located in C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Assembly) is outdated? I'm asking this as Posh-SSH was previously installed in version 2.X.X.

**Comment by MVKozlov** [comment]
```
SHA256          549E5251289F56EC3E89559666A7B499E1D550B2E0F44BEEF8A983E7B66B2B37       Renci.SshNet.dll
```
it looks like #284
@Boppel, please try
``` powershell
Import-Module Posh-SSH
[System.AppDomain]::CurrentDomain.GetAssemblies() | ? { $_.Location -like '*ssh*' }
```
in the output you should see dll from C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Assembly

and... you have latest Posh-SSH version ?

Posh-SSH.psm1 should start with
``` powershell
if ($PSVersionTable.PSVersion.Major -eq 5) {
    Add-Type -Path "$PSScriptRoot/Assembly/Newtonsoft.Json.dll"
}

# force load Renci and dependency do to MS including Renci in Windows 2019 Storage Server.
if ($PSVersionTable.PSVersion.Major -eq 5) {
    Add-Type -Path "$PSScriptRoot/Assembly/SshNet.Security.Cryptography.dll"
    Add-Type -Path "$PSScriptRoot/Assembly/Renci.SshNet.dll"
    
}
```

**Comment by Boppel** [comment]
@MVKozlov 

.dlls are present and Posh-SSH 3.0.0 is installed:
![image](https://user-images.githubusercontent.com/618960/134140557-29e14c6d-f122-4eef-aad4-7fdb5b882d28.png)

after running
`Import-Module Posh-SSH
[System.AppDomain]::CurrentDomain.GetAssemblies() | ? { $_.Location -like '*ssh*' }`

i get this result:
![image](https://user-images.githubusercontent.com/618960/134140925-91d9fae3-6ccf-4b9a-88d4-f74ec4124746.png)

after looking into #284 I feel dumb - I had looked into this very issue before. Sorry for any inconvenience.
Gonna try the beta build and if that won't fix my issues, I now know what to do :)

**Comment by MVKozlov** [comment]
@Boppel all the betas are 3.0.0 so try to reinstall to latest release
