### ISSUE TITLE
Is there a way to send Ctrl+C over the SSH session?

### ISSUE THREAD

**Issue by Retr0sec7** [darkoperator/Posh-SSH#509]
Hello, I'm connecting to a Linux remote host in which one of the commands that I send over the SSH session leaves the bash terminal listening for ping results over another host. In order to scape this listening state, I must do a Ctrl+C combination, but I can't find a way do it. Does this tool sipport this? OR is there any other way I can execute a Ctrl+C with a written command on bash?

**Comment by darkoperator** [comment]
It has been something I have tried to figure but have not had success withSent from my iPhoneOn Feb 14, 2023, at 12:05 PM, Retr0sec7 ***@***.***> wrote:﻿
Hello, I'm connecting to a Linux remote host in which one of the commands that I send over the SSH session leaves the bash terminal listening for ping results over another host. In order to scape this listening state, I must do a Ctrl+C combination, but I can't find a way do it. Does this tool sipport this? OR is there any other way I can execute a Ctrl+C with a written command on bash?

**Comment by MVKozlov** [comment]
You can limit number of ping

**Comment by darkoperator** [comment]
Ping -c <count> hostipSent from my iPhoneOn Feb 14, 2023, at 12:19 PM, Max Kozlov ***@***.***> wrote:﻿
You can limit number of ping
