### ISSUE TITLE
Posh-SSH version 3.1 is a normal release?

### ISSUE THREAD

**Issue by ErsiaJin** [darkoperator/Posh-SSH#551]
Dear

I was using posh-ssh just fine until a few weeks ago.
However, a build error suddenly occurred today and I checked and found that the error occurred in the posh-ssh package. As a result, it occurred while receiving the latest version, 3.1.

##[error]Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.1\Assembly\Renci.SshNet.dll' because it does not exist."

The error appears to be caused by the presence of the Renci.SshNetDev.dll file rather than the Renci.SshNet.dll file in the 3.1 package.

I have a question here.
![image](https://github.com/darkoperator/Posh-SSH/assets/7437132/027cd8d0-cbc1-40ad-9138-033c2dd83811)

I haven't heard of a separate release on Github, but version 3.1 is posted in the Powershell Gallery.

I would like to know if that version is a normal release.

**Comment by darkoperator** [comment]
Its a normal release, will check what the error could be. I recommend for production to never pull the latest but tie it to a known tested versionSent from my iPhoneOn Oct 23, 2023, at 4:07 AM, ErsiaJin ***@***.***> wrote:﻿
Dear
I was using posh-ssh just fine until a few weeks ago.
However, a build error suddenly occurred today and I checked and found that the error occurred in the posh-ssh package. As a result, it occurred while receiving the latest version, 3.1.
##[error]Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.1\Assembly\Renci.SshNet.dll' because it does not exist."
The error appears to have occurred because the Renci.SshNetDev.dll file exists in the 3.1 package.
I have a question here.

I haven't heard of a separate release on Github, but version 3.1 is posted in the Powershell Gallery.
I would like to know if that version is a normal release.

**Comment by darkoperator** [comment]
What command is producing the path error? To try and replicate? I renamed the DLL and compiled against the renamed version due to problems on specific roles in Windows where MS ships a very old version of the library and causes conflicts. I have not updated the changelog or published a new release here due to time constraints.

**Comment by darkoperator** [comment]
Found the error, will fix and push a new version in a couple of minutes

**Comment by darkoperator** [comment]
Pushed 3.1.1 and unlisted 3.1. Please test
