### ISSUE TITLE
SSH executing commands to Palo Alto firewall

### ISSUE THREAD

**Issue by bipsendk** [darkoperator/Posh-SSH#577]
I am trying to issue the "show system info" command via SSH on a Palo Alto firewall - but no success

```
# Opening session
$session = New-SSHSession $Script:computer -Credential $Script:credential -Port $Script:port -AcceptKey  -ErrorAction "Stop"
$sessionId = $session.SessionId

# Execute command
$stream = New-SSHShellStream -SessionId $sessionId -Columns 80 -Rows 256  
$stream.Write("show system info")
$stream.read()
```

This just gives me:

```
Last login: Fri Jun  7 11:35:07 2024 from 172.20.153.150



Number of failed attempts since last successful login: 0



show system info
```

Trying to do an additional $stream.read() a few seconds later:

```
user@fwl01> show 

user@fwl01> show system 

user@fwl01> show system info

```

I never get the expected output.

Any hints on how to handle this ?

**Comment by darkoperator** [comment]
Remeber to add a carriage return in the command. So it is interpreted as an enter and have a sleep after the commandSent from my iPhoneOn Jun 7, 2024, at 5:40 AM, bipsendk ***@***.***> wrote:﻿
I am trying to issue the "show system info" command via SSH on a Palo Alto firewall - but no success
# Opening session
$session = New-SSHSession $Script:computer -Credential $Script:credential -Port $Script:port -AcceptKey  -ErrorAction "Stop"
$sessionId = $session.SessionId

# Execute command
$stream = New-SSHShellStream -SessionId $sessionId -Columns 80 -Rows 256  
$stream.Write("show system info")
$stream.read()

This just gives me:
Last login: Fri Jun  7 11:35:07 2024 from 172.20.153.150



Number of failed attempts since last successful login: 0



show system info

Trying to do an additional $stream.read() a few seconds later:
***@***.***> show 

***@***.***> show system 

***@***.***> show system info


I never get the expected output.
Any hints on how to handle this ?

**Comment by bipsendk** [comment]
Adding a `r in the command then gives this read output:

```
show 
exivity_RO@nCNM-fwl-07-01> show system 
exivity_RO@nCNM-fwl-07-01> show system info
WARNING: terminal is not fully functional
-  (press RETURN)
```

**Comment by bipsendk** [comment]
Update - adding `r`n helped ...
