### ISSUE TITLE
feat: wildcard pattern matching

### ISSUE THREAD

**Issue by Agent-E11** [darkoperator/Posh-SSH#589]
It would be very nice to be able to supply a wildcard pattern to `Get-SFTPChildItem`. Currently, if you were to run
```ps1
Get-SFTPChildItem -SessionId 0 -Path /pattern*
```
You would get the error:
```
Path /pattern* doesn't exist on the target host.
```

This wildcard matching is possible in the default `sftp` program that comes with Redhat:
```sh
sftp user@host:/pattern*
```
and in the PowerShell cmdlet `Get-ChildItem`:
```ps1
Get-ChildItem -Path C:\pattern*
```
Based on the discrepancy between the functionality of `Get-ChildItem` and `Get-SFTPChildItem`, this may be considered a bug.

**Comment by darkoperator** [comment]
calling it a bug would be stretching it  :)  whould be easy to do say for file or directory names in a given path, for the path it self to enumerate will have to look at it  since the library does not support use of wildcard and would need to write a wrapper to go one level down from the wildcard enumerate directories only and match does and then for those that match then enumerate their content

**Comment by darkoperator** [comment]
was not as difficult as I thought 

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/0ea1f4d5-dad9-4c19-8f49-e2bb27b4f63b">

Added also a parameter name where wildcards can also be used in the next release 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/40b83000-42c0-435e-afee-d802532b8cd4">

**Comment by darkoperator** [comment]
in latest release 3.2.2
